apiVersion: v1
kind: Service
metadata:
  name: react-client
  labels:
    app: react-client
spec:
  type: ClusterIP
  selector:
    app: react-client
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
